<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTK" Version="4.9.4" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../SharpFAI.Editor.Core/SharpFAI.Editor.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="../SharpFAI.Editor.Resources/**">
            <Link>Resources/%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
